name: Upload to Object Storage

on:
  push:
    paths:
      - 'website-portfolio/index.html'
      - 'website-portfolio/AskerKakhramanov-CV.doc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Configure s3cmd
        run: |
          echo -e "[default]\naccess_key=${{ secrets.ACCESS_KEY }}\nsecret_key=${{ secrets.SECRET_KEY }}\nhost_base=${{ secrets.HOST_BASE }}\nhost_bucket=${{ secrets.HOST_BUCKET }}\nbucket_location=${{ secrets.REGION }}" > ~/.s3cfg

      - name: Upload 'index.html', 'AskerKakhramanov-CV.doc' to Object Storage 1
        run: |
          s3cmd put website-portfolio/index.html s3://${{ secrets.OBJECT_STORAGE_1 }}/index.html
          s3cmd put website-portfolio/AskerKakhramanov-CV.doc s3://${{ secrets.OBJECT_STORAGE_1 }}/AskerKakhramanov-CV.doc

      - name: Upload 'index.html', 'AskerKakhramanov-CV.doc' to Object Storage 2
        run: |
          s3cmd put website-portfolio/index.html s3://${{ secrets.OBJECT_STORAGE_2 }}/index.html
          s3cmd put website-portfolio/AskerKakhramanov-CV.doc s3://${{ secrets.OBJECT_STORAGE_2 }}/AskerKakhramanov-CV.doc